//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoiseCalculator.Infrastructure.Pdf.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReportResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoiseCalculator.Infrastructure.Pdf.Resources.ReportResource", typeof(ReportResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment: {0}.
        /// </summary>
        internal static string CommentFormatString {
            get {
                return ResourceManager.GetString("CommentFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: {0}.
        /// </summary>
        internal static string DateFormatString {
            get {
                return ResourceManager.GetString("DateFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise Level (dBA).
        /// </summary>
        internal static string HeadingNoiseLevel {
            get {
                return ResourceManager.GetString("HeadingNoiseLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise Protection.
        /// </summary>
        internal static string HeadingNoiseProtection {
            get {
                return ResourceManager.GetString("HeadingNoiseProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string HeadingRole {
            get {
                return ResourceManager.GetString("HeadingRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string HeadingTitle {
            get {
                return ResourceManager.GetString("HeadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Time.
        /// </summary>
        internal static string HeadingWorkTime {
            get {
                return ResourceManager.GetString("HeadingWorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to measured.
        /// </summary>
        internal static string NoiseMeassured {
            get {
                return ResourceManager.GetString("NoiseMeassured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant: {0}.
        /// </summary>
        internal static string PlantFormatString {
            get {
                return ResourceManager.GetString("PlantFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession: {0}.
        /// </summary>
        internal static string ProfessionFormatString {
            get {
                return ResourceManager.GetString("ProfessionFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated noise exposure.
        /// </summary>
        internal static string ReportTitle {
            get {
                return ResourceManager.GetString("ReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string SelectedTaskNoiseLevelNotApplicable {
            get {
                return ResourceManager.GetString("SelectedTaskNoiseLevelNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {0}%.
        /// </summary>
        internal static string TotalPercentageFormatString {
            get {
                return ResourceManager.GetString("TotalPercentageFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username: {0}.
        /// </summary>
        internal static string UserFormatString {
            get {
                return ResourceManager.GetString("UserFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} h {1} min.
        /// </summary>
        internal static string WorkTimeFormatString {
            get {
                return ResourceManager.GetString("WorkTimeFormatString", resourceCulture);
            }
        }
    }
}
