//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoiseCalculator.UI.Web.Areas.Admin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoiseCalculator.UI.Web.Areas.Admin.Resources.AdminResources", typeof(AdminResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string AdminColumnLabelUsername {
            get {
                return ResourceManager.GetString("AdminColumnLabelUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string AdminLabelUsername {
            get {
                return ResourceManager.GetString("AdminLabelUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string ButtonAddNew {
            get {
                return ResourceManager.GetString("ButtonAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSubmit {
            get {
                return ResourceManager.GetString("ButtonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ColumnEdit {
            get {
                return ResourceManager.GetString("ColumnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string ColumnRemove {
            get {
                return ResourceManager.GetString("ColumnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Users.
        /// </summary>
        public static string ContextMenuAdministratorUsers {
            get {
                return ResourceManager.GetString("ContextMenuAdministratorUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helictoper: Noise Protection.
        /// </summary>
        public static string ContextMenuHelicopterNoiseProtection {
            get {
                return ResourceManager.GetString("ContextMenuHelicopterNoiseProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helicopter: Tasks.
        /// </summary>
        public static string ContextMenuHelicopterTasks {
            get {
                return ResourceManager.GetString("ContextMenuHelicopterTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helicopter: Types.
        /// </summary>
        public static string ContextMenuHelicopterTypes {
            get {
                return ResourceManager.GetString("ContextMenuHelicopterTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helictoper: Work Interval.
        /// </summary>
        public static string ContextMenuHelictoperWorkInterval {
            get {
                return ResourceManager.GetString("ContextMenuHelictoperWorkInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise Protection.
        /// </summary>
        public static string ContextMenuNoiseProtection {
            get {
                return ResourceManager.GetString("ContextMenuNoiseProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string ContextMenuTasks {
            get {
                return ResourceManager.GetString("ContextMenuTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Removal.
        /// </summary>
        public static string DeleteConfirmationWindowTitle {
            get {
                return ResourceManager.GetString("DeleteConfirmationWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition Name.
        /// </summary>
        public static string GenericDefinitionColumnDefinitionName {
            get {
                return ResourceManager.GetString("GenericDefinitionColumnDefinitionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string GenericDefinitionLabelTitle {
            get {
                return ResourceManager.GetString("GenericDefinitionLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Exposure.
        /// </summary>
        public static string GenericTaskAllowedExposure {
            get {
                return ResourceManager.GetString("GenericTaskAllowedExposure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string GenericTaskLanguage {
            get {
                return ResourceManager.GetString("GenericTaskLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise Level.
        /// </summary>
        public static string GenericTaskNoiseLevel {
            get {
                return ResourceManager.GetString("GenericTaskNoiseLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise Protection.
        /// </summary>
        public static string GenericTaskNoiseProtection {
            get {
                return ResourceManager.GetString("GenericTaskNoiseProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string GenericTaskRole {
            get {
                return ResourceManager.GetString("GenericTaskRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string GenericTaskTitle {
            get {
                return ResourceManager.GetString("GenericTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string GenericTranslationLabelTitle {
            get {
                return ResourceManager.GetString("GenericTranslationLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        public static string HeadingTranslations {
            get {
                return ResourceManager.GetString("HeadingTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helicopter.
        /// </summary>
        public static string HelicopterTaskColumnHelicopter {
            get {
                return ResourceManager.GetString("HelicopterTaskColumnHelicopter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise Protection.
        /// </summary>
        public static string HelicopterTaskColumnNoiseProtectionDefinition {
            get {
                return ResourceManager.GetString("HelicopterTaskColumnNoiseProtectionDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string HelicopterTaskColumnPercentage {
            get {
                return ResourceManager.GetString("HelicopterTaskColumnPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Interval.
        /// </summary>
        public static string HelicopterTaskColumnWorkInterval {
            get {
                return ResourceManager.GetString("HelicopterTaskColumnWorkInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant Task.
        /// </summary>
        public static string RotationTaskColumnAssistantTask {
            get {
                return ResourceManager.GetString("RotationTaskColumnAssistantTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string RotationTaskColumnLanguage {
            get {
                return ResourceManager.GetString("RotationTaskColumnLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Task.
        /// </summary>
        public static string RotationTaskColumnOperatorTask {
            get {
                return ResourceManager.GetString("RotationTaskColumnOperatorTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string RotationTaskColumnTitle {
            get {
                return ResourceManager.GetString("RotationTaskColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string RotationTaskDefinitionLabelTitle {
            get {
                return ResourceManager.GetString("RotationTaskDefinitionLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        public static string RotationTaskDefinitionLabelTranslations {
            get {
                return ResourceManager.GetString("RotationTaskDefinitionLabelTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant Task.
        /// </summary>
        public static string RotationTaskLabelAssistantTask {
            get {
                return ResourceManager.GetString("RotationTaskLabelAssistantTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string RotationTaskLabelLanguage {
            get {
                return ResourceManager.GetString("RotationTaskLabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Task.
        /// </summary>
        public static string RotationTaskLabelOperatorTask {
            get {
                return ResourceManager.GetString("RotationTaskLabelOperatorTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string RotationTaskLabelTitle {
            get {
                return ResourceManager.GetString("RotationTaskLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition Name.
        /// </summary>
        public static string TaskDefinitionColumnDefinitionName {
            get {
                return ResourceManager.GetString("TaskDefinitionColumnDefinitionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Type.
        /// </summary>
        public static string TaskDefinitionColumnRoleType {
            get {
                return ResourceManager.GetString("TaskDefinitionColumnRoleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Type.
        /// </summary>
        public static string TaskDefinitionLabelRoleType {
            get {
                return ResourceManager.GetString("TaskDefinitionLabelRoleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TaskDefinitionLabelTitle {
            get {
                return ResourceManager.GetString("TaskDefinitionLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise Protection.
        /// </summary>
        public static string TaskFormHelideckHelicopterNoiseProtectionLabel {
            get {
                return ResourceManager.GetString("TaskFormHelideckHelicopterNoiseProtectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helicopter.
        /// </summary>
        public static string TaskFormHelideckHelicopterTypeLabel {
            get {
                return ResourceManager.GetString("TaskFormHelideckHelicopterTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Interval.
        /// </summary>
        public static string TaskFormHelideckHelicopterWorkIntervalLabel {
            get {
                return ResourceManager.GetString("TaskFormHelideckHelicopterWorkIntervalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant.
        /// </summary>
        public static string TaskFormRegularAssistantLabel {
            get {
                return ResourceManager.GetString("TaskFormRegularAssistantLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise Measured.
        /// </summary>
        public static string TaskFormRegularNoiseMeasuredLabel {
            get {
                return ResourceManager.GetString("TaskFormRegularNoiseMeasuredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string TaskFormRegularOperatorLabel {
            get {
                return ResourceManager.GetString("TaskFormRegularOperatorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of daily noise dosage.
        /// </summary>
        public static string TaskFormRegularPercentageLabel {
            get {
                return ResourceManager.GetString("TaskFormRegularPercentageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string TaskFormRegularWorkTimeLabel {
            get {
                return ResourceManager.GetString("TaskFormRegularWorkTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Time As.
        /// </summary>
        public static string TaskFormWorkTimeAsLabel {
            get {
                return ResourceManager.GetString("TaskFormWorkTimeAsLabel", resourceCulture);
            }
        }
    }
}
