//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoiseCalculator.UI.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TaskResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaskResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoiseCalculator.UI.Web.Resources.TaskResources", typeof(TaskResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise Calculator.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string HoursUnit {
            get {
                return ResourceManager.GetString("HoursUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        public static string IndexButtonAddTask {
            get {
                return ResourceManager.GetString("IndexButtonAddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print PDF.
        /// </summary>
        public static string IndexButtonCreatePdf {
            get {
                return ResourceManager.GetString("IndexButtonCreatePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Tasks.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Daily Dosage.
        /// </summary>
        public static string IndexTotalDailyDosageLabel {
            get {
                return ResourceManager.GetString("IndexTotalDailyDosageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string LayoutUserLabel {
            get {
                return ResourceManager.GetString("LayoutUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string MinutesUnit {
            get {
                return ResourceManager.GetString("MinutesUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work under the calculated noise level is not allowed!.
        /// </summary>
        public static string NoiseLevelStatusTextCritical {
            get {
                return ResourceManager.GetString("NoiseLevelStatusTextCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise level is below the upper limt and is considered safe.
        /// </summary>
        public static string NoiseLevelStatusTextNormal {
            get {
                return ResourceManager.GetString("NoiseLevelStatusTextNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise level is approaching allowed limits.
        /// </summary>
        public static string NoiseLevelStatusTextWarning {
            get {
                return ResourceManager.GetString("NoiseLevelStatusTextWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string RemoveTaskConfirmationButtonClose {
            get {
                return ResourceManager.GetString("RemoveTaskConfirmationButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveTaskConfirmationButtonRemove {
            get {
                return ResourceManager.GetString("RemoveTaskConfirmationButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Task?.
        /// </summary>
        public static string RemoveTaskConfirmationTitle {
            get {
                return ResourceManager.GetString("RemoveTaskConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string SelectedTaskEditLabel {
            get {
                return ResourceManager.GetString("SelectedTaskEditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise Level.
        /// </summary>
        public static string SelectedTaskNoiseLevelLabel {
            get {
                return ResourceManager.GetString("SelectedTaskNoiseLevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise Protection.
        /// </summary>
        public static string SelectedTaskNoiseProtectionLabel {
            get {
                return ResourceManager.GetString("SelectedTaskNoiseProtectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Daily Dosage.
        /// </summary>
        public static string SelectedTaskPercentageDailyDosageLabel {
            get {
                return ResourceManager.GetString("SelectedTaskPercentageDailyDosageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string SelectedTaskRemoveLabel {
            get {
                return ResourceManager.GetString("SelectedTaskRemoveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Time.
        /// </summary>
        public static string SelectedTaskWorkTimeLabel {
            get {
                return ResourceManager.GetString("SelectedTaskWorkTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select One --.
        /// </summary>
        public static string SelectOne {
            get {
                return ResourceManager.GetString("SelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Task.
        /// </summary>
        public static string TaskDialogButtonUseTask {
            get {
                return ResourceManager.GetString("TaskDialogButtonUseTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        public static string TaskDialogTitle {
            get {
                return ResourceManager.GetString("TaskDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TaskFormButtonClose {
            get {
                return ResourceManager.GetString("TaskFormButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        public static string TaskFormButtonSubmitAdd {
            get {
                return ResourceManager.GetString("TaskFormButtonSubmitAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string TaskFormButtonSubmitEdit {
            get {
                return ResourceManager.GetString("TaskFormButtonSubmitEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise Protection.
        /// </summary>
        public static string TaskFormHelideckHelicopterNoiseProtectionLabel {
            get {
                return ResourceManager.GetString("TaskFormHelideckHelicopterNoiseProtectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helicopter.
        /// </summary>
        public static string TaskFormHelideckHelicopterTypeLabel {
            get {
                return ResourceManager.GetString("TaskFormHelideckHelicopterTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Interval.
        /// </summary>
        public static string TaskFormHelideckHelicopterWorkIntervalLabel {
            get {
                return ResourceManager.GetString("TaskFormHelideckHelicopterWorkIntervalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant.
        /// </summary>
        public static string TaskFormRegularAssistantLabel {
            get {
                return ResourceManager.GetString("TaskFormRegularAssistantLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise Measured.
        /// </summary>
        public static string TaskFormRegularNoiseMeasuredLabel {
            get {
                return ResourceManager.GetString("TaskFormRegularNoiseMeasuredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string TaskFormRegularOperatorLabel {
            get {
                return ResourceManager.GetString("TaskFormRegularOperatorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        public static string TaskFormRegularPercentageLabel {
            get {
                return ResourceManager.GetString("TaskFormRegularPercentageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work specified as.
        /// </summary>
        public static string TaskFormRegularWorkAmountTypeLabel {
            get {
                return ResourceManager.GetString("TaskFormRegularWorkAmountTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string TaskFormRegularWorkTimeLabel {
            get {
                return ResourceManager.GetString("TaskFormRegularWorkTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string TaskRoleLabel {
            get {
                return ResourceManager.GetString("TaskRoleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string TaskTitleLabel {
            get {
                return ResourceManager.GetString("TaskTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise protection must be selected..
        /// </summary>
        public static string ValidationErrorHelicopterNoiseLevelRequired {
            get {
                return ResourceManager.GetString("ValidationErrorHelicopterNoiseLevelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helicopter must be selected..
        /// </summary>
        public static string ValidationErrorHelicopterTypeRequired {
            get {
                return ResourceManager.GetString("ValidationErrorHelicopterTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work interval must be selected..
        /// </summary>
        public static string ValidationErrorHelicopterWorkIntervalRequired {
            get {
                return ResourceManager.GetString("ValidationErrorHelicopterWorkIntervalRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation is invalid for noise levels that are 7 dBA or more above the guideline..
        /// </summary>
        public static string ValidationErrorNoiseLevelToHighAboveGuidline {
            get {
                return ResourceManager.GetString("ValidationErrorNoiseLevelToHighAboveGuidline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ValidationErrorSummaryClose {
            get {
                return ResourceManager.GetString("ValidationErrorSummaryClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors found in submitted data.
        /// </summary>
        public static string ValidationErrorSummaryTitle {
            get {
                return ResourceManager.GetString("ValidationErrorSummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task work time must be specified, either as hours/minutes or percentage of daily dosage.
        /// </summary>
        public static string ValidationErrorWorkTimeRequired {
            get {
                return ResourceManager.GetString("ValidationErrorWorkTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
