//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoiseCalculator.UI.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TaskResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaskResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoiseCalculator.UI.Web.Resources.TaskResources", typeof(TaskResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise Calculator.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If calculated noise dosage is 100% the worker must stay in areas with a noise level less than 80dBA the rest of the day. The worker can also not perform any work with a noise level above 80 dBA..
        /// </summary>
        public static string Footer80dBA {
            get {
                return ResourceManager.GetString("Footer80dBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The calculation of noise exposure has taken breaks (like moving to a new location) into account and made corrections to the meassured noise levels share of a normal work cycle. The provided work time reflects the total time spent on the task, including the non noisy work. If there are considerable changes in the normal work cycle, contact an industrial hygenist..
        /// </summary>
        public static string FooterDynamicCorrectionForMeasuredNoiseLevel {
            get {
                return ResourceManager.GetString("FooterDynamicCorrectionForMeasuredNoiseLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following conditions apply regarding noise protection. The noise protection should be well maintained and used correctly. When using &quot;universal ear plugs&quot;, individual training should be given regarding usage and insertion. When using custom molded ear plugs, insertion training should be given. Ref:GL0169, tabell 4-1..
        /// </summary>
        public static string FooterDynamicNoiseProtection {
            get {
                return ResourceManager.GetString("FooterDynamicNoiseProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The risk analysis for noisy work is valid for area noise less than or equal to 90 dBA. Perform field measurements when the area noise is above 90 dBA or if the work is performed in areas....
        /// </summary>
        public static string FooterDynamicValidForAreaNoiseUpTo90dBA {
            get {
                return ResourceManager.GetString("FooterDynamicValidForAreaNoiseUpTo90dBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tool is based upon noise guideline GL0169..
        /// </summary>
        public static string FooterGL0169 {
            get {
                return ResourceManager.GetString("FooterGL0169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By single noise protection we mean earplugs or earmuffs. By double noise protection we mean earplugs used together with earmuffs..
        /// </summary>
        public static string FooterNoiseProtectionDefinition {
            get {
                return ResourceManager.GetString("FooterNoiseProtectionDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string HoursUnit {
            get {
                return ResourceManager.GetString("HoursUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        public static string IndexButtonAddTask {
            get {
                return ResourceManager.GetString("IndexButtonAddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print PDF.
        /// </summary>
        public static string IndexButtonCreatePdf {
            get {
                return ResourceManager.GetString("IndexButtonCreatePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All.
        /// </summary>
        public static string IndexButtonRemoveAll {
            get {
                return ResourceManager.GetString("IndexButtonRemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tasks to calculate your noise exposure.
        /// </summary>
        public static string IndexSubtitle {
            get {
                return ResourceManager.GetString("IndexSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Tasks.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of daily noise dosage.
        /// </summary>
        public static string IndexTotalDailyDosageLabel {
            get {
                return ResourceManager.GetString("IndexTotalDailyDosageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageNameEnglish {
            get {
                return ResourceManager.GetString("LanguageNameEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian.
        /// </summary>
        public static string LanguageNameNorwegian {
            get {
                return ResourceManager.GetString("LanguageNameNorwegian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown language.
        /// </summary>
        public static string LanguageNameUnknown {
            get {
                return ResourceManager.GetString("LanguageNameUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string LayoutUserLabel {
            get {
                return ResourceManager.GetString("LayoutUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string MinutesUnit {
            get {
                return ResourceManager.GetString("MinutesUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string RemoveAllConfirmationButtonClose {
            get {
                return ResourceManager.GetString("RemoveAllConfirmationButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All.
        /// </summary>
        public static string RemoveAllConfirmationButtonRemove {
            get {
                return ResourceManager.GetString("RemoveAllConfirmationButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all tasks in the tasklist?.
        /// </summary>
        public static string RemoveAllConfirmationDescription {
            get {
                return ResourceManager.GetString("RemoveAllConfirmationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All?.
        /// </summary>
        public static string RemoveAllConformationTitle {
            get {
                return ResourceManager.GetString("RemoveAllConformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string RemoveTaskConfirmationButtonClose {
            get {
                return ResourceManager.GetString("RemoveTaskConfirmationButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveTaskConfirmationButtonRemove {
            get {
                return ResourceManager.GetString("RemoveTaskConfirmationButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Task?.
        /// </summary>
        public static string RemoveTaskConfirmationTitle {
            get {
                return ResourceManager.GetString("RemoveTaskConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string SelectedTaskEditLabel {
            get {
                return ResourceManager.GetString("SelectedTaskEditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise Level.
        /// </summary>
        public static string SelectedTaskNoiseLevelLabel {
            get {
                return ResourceManager.GetString("SelectedTaskNoiseLevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not applicable.
        /// </summary>
        public static string SelectedTaskNoiseLevelNotApplicable {
            get {
                return ResourceManager.GetString("SelectedTaskNoiseLevelNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Measured).
        /// </summary>
        public static string SelectedTaskNoiseMeasured {
            get {
                return ResourceManager.GetString("SelectedTaskNoiseMeasured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise Protection.
        /// </summary>
        public static string SelectedTaskNoiseProtectionLabel {
            get {
                return ResourceManager.GetString("SelectedTaskNoiseProtectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Daily Dosage.
        /// </summary>
        public static string SelectedTaskPercentageDailyDosageLabel {
            get {
                return ResourceManager.GetString("SelectedTaskPercentageDailyDosageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string SelectedTaskRemoveLabel {
            get {
                return ResourceManager.GetString("SelectedTaskRemoveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Time.
        /// </summary>
        public static string SelectedTaskWorkTimeLabel {
            get {
                return ResourceManager.GetString("SelectedTaskWorkTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select One --.
        /// </summary>
        public static string SelectOne {
            get {
                return ResourceManager.GetString("SelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        public static string TaskDialogAddTitle {
            get {
                return ResourceManager.GetString("TaskDialogAddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Task.
        /// </summary>
        public static string TaskDialogButtonUseTask {
            get {
                return ResourceManager.GetString("TaskDialogButtonUseTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Task.
        /// </summary>
        public static string TaskDialogEditTitle {
            get {
                return ResourceManager.GetString("TaskDialogEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TaskFormButtonClose {
            get {
                return ResourceManager.GetString("TaskFormButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        public static string TaskFormButtonSubmitAdd {
            get {
                return ResourceManager.GetString("TaskFormButtonSubmitAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string TaskFormButtonSubmitEdit {
            get {
                return ResourceManager.GetString("TaskFormButtonSubmitEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise Protection.
        /// </summary>
        public static string TaskFormHelideckHelicopterNoiseProtectionLabel {
            get {
                return ResourceManager.GetString("TaskFormHelideckHelicopterNoiseProtectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helicopter.
        /// </summary>
        public static string TaskFormHelideckHelicopterTypeLabel {
            get {
                return ResourceManager.GetString("TaskFormHelideckHelicopterTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Interval.
        /// </summary>
        public static string TaskFormHelideckHelicopterWorkIntervalLabel {
            get {
                return ResourceManager.GetString("TaskFormHelideckHelicopterWorkIntervalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant.
        /// </summary>
        public static string TaskFormRegularAssistantLabel {
            get {
                return ResourceManager.GetString("TaskFormRegularAssistantLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise Measured.
        /// </summary>
        public static string TaskFormRegularNoiseMeasuredLabel {
            get {
                return ResourceManager.GetString("TaskFormRegularNoiseMeasuredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string TaskFormRegularOperatorLabel {
            get {
                return ResourceManager.GetString("TaskFormRegularOperatorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        public static string TaskFormRegularPercentageLabel {
            get {
                return ResourceManager.GetString("TaskFormRegularPercentageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string TaskFormRegularWorkTimeLabel {
            get {
                return ResourceManager.GetString("TaskFormRegularWorkTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work time is split equally on operator and assistant..
        /// </summary>
        public static string TaskFormRotationWorkTimeSplitComment {
            get {
                return ResourceManager.GetString("TaskFormRotationWorkTimeSplitComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Time As.
        /// </summary>
        public static string TaskFormWorkTimeAsLabel {
            get {
                return ResourceManager.GetString("TaskFormWorkTimeAsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string TaskRoleLabel {
            get {
                return ResourceManager.GetString("TaskRoleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string TaskTitleLabel {
            get {
                return ResourceManager.GetString("TaskTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise protection must be selected..
        /// </summary>
        public static string ValidationErrorHelicopterNoiseLevelRequired {
            get {
                return ResourceManager.GetString("ValidationErrorHelicopterNoiseLevelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helicopter must be selected..
        /// </summary>
        public static string ValidationErrorHelicopterTypeRequired {
            get {
                return ResourceManager.GetString("ValidationErrorHelicopterTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work interval must be selected..
        /// </summary>
        public static string ValidationErrorHelicopterWorkIntervalRequired {
            get {
                return ResourceManager.GetString("ValidationErrorHelicopterWorkIntervalRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The measured noise level is more than 6 dBA above what the detailed risk analysis in GL0169 takes into account and it is therefore invalid. Apply noise reducing meassures and perform measure the noise level again. Contact an industrial hygenist if the noise level is still to high..
        /// </summary>
        public static string ValidationErrorNoiseLevelToHighAboveGuidline {
            get {
                return ResourceManager.GetString("ValidationErrorNoiseLevelToHighAboveGuidline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistant: The measured noise level is more than 6 dBA above what the detailed risk analysis in GL0169 takes into account and it is therefore invalid. Apply noise reducing meassures and perform measure the noise level again. Contact an industrial hygenist if the noise level is still to high..
        /// </summary>
        public static string ValidationErrorNoiseLevelToHighAboveGuidlineAssistant {
            get {
                return ResourceManager.GetString("ValidationErrorNoiseLevelToHighAboveGuidlineAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator: The measured noise level is more than 6 dBA above what the detailed risk analysis in GL0169 takes into account and it is therefore invalid. Apply noise reducing meassures and perform measure the noise level again. Contact an industrial hygenist if the noise level is still to high..
        /// </summary>
        public static string ValidationErrorNoiseLevelToHighAboveGuidlineOperator {
            get {
                return ResourceManager.GetString("ValidationErrorNoiseLevelToHighAboveGuidlineOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotations can not have duration longer than 6 hours, divided between operator and assistant..
        /// </summary>
        public static string ValidationErrorRotationMaximum6Hours {
            get {
                return ResourceManager.GetString("ValidationErrorRotationMaximum6Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ValidationErrorSummaryClose {
            get {
                return ResourceManager.GetString("ValidationErrorSummaryClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors found in submitted data.
        /// </summary>
        public static string ValidationErrorSummaryTitle {
            get {
                return ResourceManager.GetString("ValidationErrorSummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task work time must be specified, either as hours/minutes or percentage of daily dosage.
        /// </summary>
        public static string ValidationErrorWorkTimeRequired {
            get {
                return ResourceManager.GetString("ValidationErrorWorkTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
